### ISSUE TITLE
Research bicycle parking types per data source

### ISSUE THREAD

**Issue by risachi** [risachi/Code301BikeBright#28]
i.e. what the heck is a "ribbon", "art", "stnles", "unk", etc.?

**Comment by risachi** [comment]
All the types (BPStyle) of bicycle parking: staple, stnles, art, cora, cshare, hoop, ribbon, sellwd, whlock, unk

**Comment by risachi** [comment]
Covered: Y, U, N

**Comment by risachi** [comment]
Data  can be quickly pulled from here: http://opendata.arcgis.com/datasets/15d3e511f8dc425fb599b45775638178_62/data?orderBy=BikeParkType

**Comment by gsmatth** [comment]
Bike Parking by Type

CORA(9)

￼




HOOP(24)
￼



SELLWD(32)
￼


STAPLE(6182)

￼



ART(53)
￼


RIBBON(41)
￼





CSHARE(51)

￼
￼
STNL(60):  STNL does not denote the type, but the material.  can be loop, staple, and other designs


￼
￼



UNK(134)
![stnl](https://cloud.githubusercontent.com/assets/13153982/13233940/0e666950-d96b-11e5-90fa-db2bfba2c8d8.png)
![ribbon](https://cloud.githubusercontent.com/assets/13153982/13233943/1742faa2-d96b-11e5-9a98-7c086c3d4457.png)
![art](https://cloud.githubusercontent.com/assets/13153982/13233946/1a786d9c-d96b-11e5-8137-a812feace480.png)
![staple](https://cloud.githubusercontent.com/assets/13153982/13233952/25c41fe8-d96b-11e5-8ccb-42304f7e4635.png)
![sellwd](https://cloud.githubusercontent.com/assets/13153982/13233954/281f85e8-d96b-11e5-862b-0fc5c1fbb374.png)
![hoop](https://cloud.githubusercontent.com/assets/13153982/13233955/2b4549f6-d96b-11e5-8f70-5ad20321b292.png)
![cor](https://cloud.githubusercontent.com/assets/13153982/13233963/2e5d156a-d96b-11e5-92eb-cdadc917f73d.png)
