### ISSUE TITLE
Mission statement and team

### ISSUE THREAD

**Issue by gsmatth** [risachi/Code301BikeBright#3]
As a user I can view the mission statement and the project team member details on the home page

**Comment by deeheber** [comment]
For the details about each team member, I'm thinking maybe our name and then what type of bike we like to ride.

Thoughts? I'm hoping to keep it short and sweet as lots of text on a mobile device might not look so good.

**Comment by gsmatth** [comment]
I like that.  How about something short about your favorite ride or your biking experience(commuter, leisure, racing, touring, mountain versus road) and your current bike lock model?  Something like:  "An avid road and mountain bike rider for the last 20 years. My  favorite ride was the Cycle America Crater Lake summer tour.  Current favorite lock is the Kryptonite New Yorker. My current bikes include a Trek 8000 and a Specialized Roubaix Pro."

**Comment by risachi** [comment]
I just wrote up a bio for myself. I followed Doug's example.

**Comment by deeheber** [comment]
Bio for myself is also finished.
