### ISSUE TITLE
User default map

### ISSUE THREAD

**Issue by gsmatth** [risachi/Code301BikeBright#7]
As a user, I want the map to open up to my last viewed map upon initial page load

**Comment by deeheber** [comment]
Looks like controls can store state. [More info here.](https://developers.google.com/maps/documentation/javascript/controls)

**Comment by deeheber** [comment]
If we can refactor map.js into MVC format, this might be easier to implement passing in the state.

**Comment by gsmatth** [comment]
We have decided that this capability does not add enough value.  We have added more value to the map page by providing the user with the ability to show crime data, show bike parking data, and zooming into current location or a specific address.  This could be considered for a later enhancements.
