### ISSUE TITLE
Map page filter input fields

### ISSUE THREAD

**Issue by gsmatth** [risachi/Code301BikeBright#8]
As a user, I want to be able to input information to filter the map.

**Comment by deeheber** [comment]
If we're going to have an address search I found [this information](https://developers.google.com/maps/documentation/javascript/places-autocomplete) during my research that might help.

**Comment by deeheber** [comment]
Going to see if I can add an address field that pans to entered location on the map on submit.

**Comment by deeheber** [comment]
Reopening, since this is now broken. Need to refactor a bit.
